/**
 * formula/pll-formulas.ts
 * PLL 公式库（21 个 case，覆盖全部比赛场景）
 *
 * PLL 共 21 个 case（不算镜像），公式来源：J Perm 整理 + algdb.net
 */

import type { Formula } from "./types.ts";

export const PLL_FORMULAS: Formula[] = [
  {
    id: "PLL-Ua",
    category: "PLL",
    name: "U-Perm (Ua)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(U 形)",
    moves: ["R", "U'", "R", "U", "R", "U", "R", "U'", "R'", "U'", "R2"],
    recognition: "3 面已还原，1 面有 2 个对角块需要交换（U 形缺口在左前和右后）。",
    execution: "1. U 形开口对着自己 2. R U' R U R U R U' R' U' R2：11 步，顺时针版本。",
    difficulty: 2,
    tags: ["permutation-only", "edge-only"],
    source: "J Perm U-Perm Ua",
  },
  {
    id: "PLL-Ub",
    category: "PLL",
    name: "U-Perm (Ub)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(U 形镜像)",
    moves: ["R2", "U", "R", "U", "R'", "U'", "R'", "U'", "R'", "U", "R'"],
    recognition: "U-Perm 镜像，U 形开口在右前和左后。",
    execution: "1. U 形开口对着自己（镜像） 2. R2 U R U R' U' R' U' R' U R'：11 步。",
    difficulty: 2,
    tags: ["permutation-only", "edge-only"],
    source: "J Perm U-Perm Ub",
  },
  {
    id: "PLL-H",
    category: "PLL",
    name: "H-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(H 形)",
    moves: ["M2", "U", "M2", "U2", "M2", "U", "M2"],
    recognition: "对面 2 个棱块需要交换（H 形横跨对面）。",
    execution: "1. H 形横着 2. M2 U M2 U2 M2 U M2：纯 M 切片，6 步超快公式。",
    difficulty: 3,
    tags: ["permutation-only", "edge-only", "m-slice"],
    source: "H-Perm 经典公式",
  },
  {
    id: "PLL-Z",
    category: "PLL",
    name: "Z-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(Z 形)",
    moves: ["M2", "U", "M2", "U", "M", "U2", "M2", "U2", "M", "U2"],
    recognition: "2 个对角棱块需要交换（Z 形斜跨）。比 H 难。",
    execution: "1. Z 形斜着 2. M2 U M2 U M U2 M2 U2 M U2：含 M 切片 + U 转动。",
    difficulty: 4,
    tags: ["permutation-only", "edge-only", "m-slice"],
    source: "Z-Perm 公式",
  },
  {
    id: "PLL-T",
    category: "PLL",
    name: "T-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(T 形)",
    moves: ["R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'", "U'", "R", "U", "R'", "F'"],
    recognition: "2 个相邻角块 + 2 个相邻棱块同时需要交换（T 形）。最常用 PLL。",
    execution: "1. T 形缺口朝右 2. R U R' U' R' F R2 U' R' U' R U R' F'：14 步，比赛高频。",
    difficulty: 3,
    tags: ["two-sided", "corner-edge"],
    source: "T-Perm 经典公式",
  },
  {
    id: "PLL-Ja",
    category: "PLL",
    name: "J-Perm (Ja)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(J 形)",
    moves: ["R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'"],
    recognition: "1 个角块 + 2 个棱块需要循环（J 形左版本）。",
    execution: "1. J 形头部朝左 2. R U R' F' R U R' U' R' F R2 U' R'：12 步。",
    difficulty: 3,
    tags: ["two-sided", "corner-edge"],
    source: "J-Perm Ja",
  },
  {
    id: "PLL-Jb",
    category: "PLL",
    name: "J-Perm (Jb)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(J 形镜像)",
    moves: ["R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'"],
    recognition: "Ja 的镜像，J 形头部朝右。",
    execution: "1. J 形头部朝右 2. R2 U R U R' U' R' U' R U R' U R：12 步。",
    difficulty: 3,
    tags: ["two-sided", "corner-edge"],
    source: "J-Perm Jb",
  },
  {
    id: "PLL-Ra",
    category: "PLL",
    name: "R-Perm (Ra)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(R 形)",
    moves: ["L", "U2", "L'", "U2", "L", "F'", "L'", "U'", "L", "U", "L", "F", "L2"],
    recognition: "2 个相邻角块 + 2 个对角棱块需要交换（R 形左版本）。",
    execution: "1. R 形开口朝右 2. R U' R' U' R U R D R' U' R D' R'：含 D 层。",
    difficulty: 4,
    tags: ["two-sided", "corner-edge", "d-layer"],
    source: "R-Perm Ra",
  },
  {
    id: "PLL-Rb",
    category: "PLL",
    name: "R-Perm (Rb)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(R 形镜像)",
    moves: ["R'", "U2", "R", "U2", "R'", "F", "R", "U", "R'", "U'", "R'", "F'", "R2"],
    recognition: "Ra 镜像，R 形开口朝左。",
    execution: "1. R 形开口朝左 2. R' U2 R U2 R' F R U R' U' R' F' R2：13 步。",
    difficulty: 4,
    tags: ["two-sided", "corner-edge"],
    source: "R-Perm Rb",
  },
  {
    id: "PLL-F",
    category: "PLL",
    name: "F-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(F 形)",
    moves: ["R'", "U'", "F'", "R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'", "U'", "R", "U", "R'", "U", "R"],
    recognition: "2 个对面棱块 + 2 个对面角块需要交换（F 形）。",
    execution: "1. F 形竖着 2. R' U' F' R U R' U' R' F R2 U' R' U' R U R' U R：17 步最长 PLL 之一。",
    difficulty: 5,
    tags: ["two-sided", "corner-edge", "advanced"],
    source: "F-Perm 公式",
  },
  {
    id: "PLL-V",
    category: "PLL",
    name: "V-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(V 形)",
    moves: ["R'", "U", "R'", "U'", "R", "D'", "R'", "D", "R'", "U", "D'", "R2", "U'", "R2", "D", "R2"],
    recognition: "2 个对角角块 + 2 个相邻棱块需要交换（V 形）。",
    execution: "1. V 形开口朝下 2. R' U R' U' Y R' U' R U B：含 Y 轴整体旋转。",
    difficulty: 4,
    tags: ["two-sided", "corner-edge", "y-rotation"],
    source: "V-Perm 公式",
  },
  {
    id: "PLL-Y",
    category: "PLL",
    name: "Y-Perm",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(Y 形)",
    moves: ["F", "R", "U'", "R'", "U'", "R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R", "F'"],
    recognition: "2 个对角棱块 + 1 个棱块循环（Y 形）。",
    execution: "1. Y 形竖着 2. F R U' R' U' R U R' F' R U R' U' R' F R F'：16 步。",
    difficulty: 4,
    tags: ["two-sided", "advanced"],
    source: "Y-Perm 公式",
  },
  {
    id: "PLL-Na",
    category: "PLL",
    name: "N-Perm (Na)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(N 形)",
    moves: ["R", "U", "R'", "U", "R", "U", "R'", "F'", "R", "U", "R'", "U'", "R'", "F", "R2", "U'", "R'", "U2", "R", "U'", "R'"],
    recognition: "2 个角块 + 1 个棱块循环（N 形左）。",
    execution: "1. N 形头朝左 2. R U R' U R U R' U' R' U R2 U' R' U2 R U' R'：17 步。",
    difficulty: 5,
    tags: ["two-sided", "advanced"],
    source: "N-Perm Na",
  },
  {
    id: "PLL-Nb",
    category: "PLL",
    name: "N-Perm (Nb)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(N 形镜像)",
    moves: ["R'", "U", "R", "U'", "R'", "F'", "U'", "F", "R", "U", "R'", "F", "R'", "F'", "R", "U'", "R"],
    recognition: "Na 镜像，N 形头朝右，2 角块 + 1 棱块循环方向相反。",
    execution: "1. N 形头朝右 2. R' U R U R' U R U' R U R2 U R U2 R' U R：17 步。",
    difficulty: 5,
    tags: ["two-sided", "advanced"],
    source: "N-Perm Nb",
  },
  {
    id: "PLL-E",
    category: "PLL",
    name: "E-Perm (三循环棱)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(三循环)",
    moves: ["R'", "U", "L'", "D2", "L", "U'", "R", "L'", "U", "R'", "D2", "R", "U'", "L"],
    recognition: "3 个棱块需要循环（角块已就位）。最难的 PLL 之一。",
    execution: "1. 找到循环起点 2. x R U R' D R U R' D'：含 x 轴整体旋转。",
    difficulty: 5,
    tags: ["three-cycle", "edge-only", "advanced"],
    source: "E-Perm 公式",
  },
  {
    id: "PLL-Aa",
    category: "PLL",
    name: "A-Perm (Aa)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(A 形)",
    moves: ["R'", "F", "R'", "B2", "R", "F'", "R'", "B2", "R2"],
    recognition: "3 个角块需要循环 + 3 个棱块反向循环（A 形）。",
    execution: "1. 让 A 形竖着 2. x R U R' D R U R' D'：和 E-Perm 公式相同但 case 不同。",
    difficulty: 5,
    tags: ["three-cycle", "advanced"],
    source: "A-Perm Aa",
  },
  {
    id: "PLL-Ab",
    category: "PLL",
    name: "A-Perm (Ab)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(A 形镜像)",
    moves: ["R", "B'", "R", "F2", "R'", "B", "R", "F2", "R2"],
    recognition: "Aa 镜像，3 个角块 + 3 个棱块反向循环，A 形头部朝另一方向。",
    execution: "1. A 形竖着（镜像） 2. x R2 D R' U R D' R' U R'：10 步。",
    difficulty: 5,
    tags: ["three-cycle", "advanced"],
    source: "A-Perm Ab",
  },
  {
    id: "PLL-Ga",
    category: "PLL",
    name: "G-Perm (Ga)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(G 形)",
    moves: ["R2", "U", "R'", "U", "R'", "U'", "R", "U'", "R2", "D", "U'", "R'", "U", "R", "D'"],
    recognition: "2 个相邻角块 + 2 个棱块循环（G 形左）。",
    execution: "1. G 形头朝左 2. R2 U R' U R' F' R2 U R' U R F R2：14 步。",
    difficulty: 5,
    tags: ["two-sided", "advanced"],
    source: "G-Perm Ga",
  },
  {
    id: "PLL-Gb",
    category: "PLL",
    name: "G-Perm (Gb)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(G 形镜像)",
    moves: ["R'", "U'", "R", "U", "D'", "R2", "U", "R'", "U", "R", "U'", "R", "U'", "R2", "D"],
    recognition: "Ga 镜像，G 形头朝右。",
    execution: "1. G 形头朝右 2. R' U' R Y R2 U R' U R U R2 D R' U R D'：含 Y 旋转。",
    difficulty: 5,
    tags: ["two-sided", "advanced", "y-rotation"],
    source: "G-Perm Gb",
  },
  {
    id: "PLL-Gc",
    category: "PLL",
    name: "G-Perm (Gc)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(G 形变体)",
    moves: ["R2", "U'", "R", "U'", "R", "U", "R'", "U", "R2", "D'", "U", "R", "U'", "R'", "D"],
    recognition: "Ga 另一种变体，G 形头朝向不同但 2 角块 + 2 棱块需要交换。",
    execution: "1. 让 G 形头朝右下 2. R2 U' R U' R F R2 U' R U' R' F' R2：14 步。",
    difficulty: 5,
    tags: ["two-sided", "advanced"],
    source: "G-Perm Gc",
  },
  {
    id: "PLL-Gd",
    category: "PLL",
    name: "G-Perm (Gd)",
    caseImage: "🟧🟧🟧\n🟧🟧🟧\n🟧🟧🟧\n(G 形镜像变体)",
    moves: ["R", "U", "R'", "U'", "D", "R2", "U'", "R", "U'", "R'", "U", "R'", "U", "R2", "D'"],
    recognition: "Gb 镜像，G 形头朝左下但交换方向相反。",
    execution: "1. G 形头朝左下 2. R U R' Y' R2 U' R U' R' U' R2 D' R U' R' D：含 Y' 旋转。",
    difficulty: 5,
    tags: ["two-sided", "advanced", "y-rotation"],
    source: "G-Perm Gd",
  },
];

/** 按 tag 筛选 PLL 公式 */
export function filterPll(tags?: string[]): typeof PLL_FORMULAS {
  if (!tags || tags.length === 0) return PLL_FORMULAS;
  return PLL_FORMULAS.filter((f) => tags.some((t) => f.tags.includes(t)));
}
